apiVersion: loki.grafana.com/v1
kind: AlertingRule
metadata:
  name: threepilars-logging-alert
  namespace: ns1-uwl
  labels: 
    openshift.io/log-alerting: 'true'
spec:
  groups:
    - interval: 1m
      name: threepilars-logging-alert
      rules:
        - alert: TestappLogRallyCount
          annotations:
            description: Rally count
            summary: ping pong is being played
          expr: >
            sum(rate({kubernetes_namespace_name="ns1-uwl", kubernetes_pod_name=~"threepilar-uwl-example-app.*"} |= "info"[1m])) > 0.01 
          for: 1m
          labels:
            severity: warning
  tenantID: application
