apiVersion: v1
kind: Service
metadata:
  labels:
    app: threepilar-example
  name: threepilar-example-service
  namespace: ns1-uwl
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
    name: web
  selector:
    app: threepilar-example
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: threepilar-example-route
  namespace: ns1-uwl
spec:
  path: "/ping"
  to:
    kind: Service
    name: threepilar-example-service
    weight: 100
  port:
    targetPort: 8090
