apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-py
  name: test-py
  namespace: ns3
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
    name: web
  - port: 9464
    protocol: TCP
    targetPort: 9464
    name: metrics
  selector:
    app: test-py
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: test-py
  name: test-py
  namespace: ns3
spec:
  path: "/ping"
  port:
    targetPort: 8090
  to:
    kind: Service
    name: test-py
    weight: 100

