apiVersion: v1
kind: Secret
metadata:
  name: tempostack-s3
  namespace: ns1-uwl
stringData:
  bucket: <s3_bucket_name>
  endpoint: https://s3.us-west-1.amazonaws.com
  access_key_id: <>
  access_key_secret: <>
type: Opaque
